wptsync_repo_path: "{{ internal_volume }}/wpt-sync"
wptsync_repo_url: https://github.com/mozilla/wpt-sync.git
# uid of app user in docker image
docker_uid: 10001
wpt_user: wpt_user
# rebuild the docker image by default
rebuild: true
# credentials will be updated on server unless any of the environment variables
# below are unset on the control machine
update_credentials: true
# default filter sets these to false if environment variable is empty string
_credentials: "{{ lookup('env','WPT_CREDENTIALS') | default(false, true) }}"
_ssh_hgmo: "{{ lookup('env','WPT_SSH_HGMO') | default(false, true) }}"
_ssh_github: "{{ lookup('env','WPT_SSH_GITHUB') | default(false, true) }}"

# docker run paths
mount_data: "{{ internal_volume }}/data"
target_data: "/app/data"
mount_workspace: "{{ internal_volume }}/workspace"
target_workspace: "/app/workspace"
mount_repos: "{{ ebs_volume }}/repos"
target_repos: "/app/repos"
target_wptsync_repo: "/app/wpt-sync"
ssh_dir: "ssh"
wptsync_config: "{{ target_wptsync_repo }}/sync_prod.ini"
wptsync_credentials: "{{ target_data }}/credentials_prod.ini"
wptsync_github_key: "{{ target_data }}/{{ ssh_dir }}/id_github"
wptsync_hgmo_key: "{{ target_data }}/{{ ssh_dir }}/id_hgmo"
