---
- name: prepare local files for deployment
  hosts: localhost
  gather_facts: no
  tasks:
  - name: echo
    shell: echo Hello World!

- name: deploy web-platform-tests syncing service
  hosts: wptsync

  pre_tasks:
    - name: import wpt sync secrets
      shell: echo "Do something with sync.ini maybe?"

  roles:
    - { role: geerlingguy.docker,
        docker_edition: "ce",
        docker_package: "docker-{{ docker_edition }}",
        docker_package_state: "latest"}
    - wptsync_host
